import { Loader2 } from 'lucide-react';
import type { AnalysisResult } from '../types';
import Header from './Header';
import TechStackWidget from './widgets/TechStack';
import SecurityThreatsWidget from './widgets/SecurityThreats';
import RiskScoreWidget from './widgets/RiskScore';
import DomainInfoWidget from './widgets/DomainInfo';
import PortsInfoWidget from './widgets/PortsInfo';
import PerformanceWidget from './widgets/Performance';
import DnsSslWidget from './widgets/DnsSslInfo';

interface DashboardProps {
  result: AnalysisResult | null;
  isAnalyzing: boolean;
  onNewAnalysis: () => void;
}

export default function Dashboard({ result, isAnalyzing, onNewAnalysis }: DashboardProps) {
  if (isAnalyzing) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-background">
        <div className="text-center">
          <div className="relative w-20 h-20 mx-auto mb-6">
            <div className="absolute inset-0 rounded-full border-4 border-surface-alt" />
            <div className="absolute inset-0 rounded-full border-4 border-transparent border-t-primary animate-spin" />
            <div className="absolute inset-0 flex items-center justify-center">
              <Loader2 className="w-8 h-8 text-primary animate-spin" />
            </div>
          </div>
          <h2 className="text-xl font-bold text-foreground mb-2">Analyzing Website</h2>
          <p className="text-muted text-sm">Scanning for threats, tech stack, and vulnerabilities...</p>
          <div className="mt-6 flex flex-col items-center gap-2">
            <div className="flex gap-2">
              {['DNS', 'SSL', 'Threats'].map((s, i) => (
                <span key={i} className="text-xs px-2.5 py-1.5 rounded-full bg-surface-alt text-muted border border-border animate-pulse">
                  {s}
                </span>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (!result) return null;

  const handleExport = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header result={result} onExport={handleExport} onNewAnalysis={onNewAnalysis} />

      <div className="flex flex-1 overflow-hidden">
        {/* Main Content */}
        <main className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8">
          {/* Summary */}
          <div className="mb-6">
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs text-muted">Last analyzed:</span>
              <span className="text-xs text-foreground">
                {new Date(result.analyzedAt).toLocaleString()}
              </span>
            </div>
            <p className="text-sm text-muted leading-relaxed max-w-3xl">
              {result.summary}
            </p>
          </div>

          {/* Top Row: Risk Score + key info */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
            <RiskScoreWidget score={result.riskScore} />
            <DomainInfoWidget info={result.domainInfo} domain={result.domain} />
            <DnsSslWidget info={result.dnsSsl} />
          </div>

          {/* Security Threats - Full width */}
          <div className="mb-6">
            <SecurityThreatsWidget threats={result.securityThreats} />
          </div>

          {/* Two-column row */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-6">
            <PerformanceWidget metrics={result.performance} />
            <PortsInfoWidget ports={result.ports} />
          </div>

          {/* Tech Stack - Full width */}
          <div className="mb-6">
            <TechStackWidget items={result.techStack} />
          </div>

          {/* Print-only PDF export note */}
          <div className="hidden print:block text-center text-xs text-muted mt-8 pt-4 border-t border-border">
            Report generated by Cyber Analysis Platform — {new Date().toLocaleString()}
          </div>
        </main>
      </div>
    </div>
  );
}
